export const mockTasks = [
    {
        id: 1,
        title: "Добавить фильтрацию",
        description: "Нужно реализовать фильтр по статусу и пользователю",
        status: "в работе",
        type: "bug",
        author: { username: "ivanov", email: "ivanov@example.com", fullName: "Иванов И.И." },
        executor: { username: "petrov", email: "petrov@example.com", fullName: "Петров П.П." },
    },
    {
        id: 2,
        title: "Реализовать логин",
        description: "Сделать форму входа и валидацию",
        status: "завершена",
        type: "task",
        author: { username: "darta", email: "darta@example.com", fullName: "Дартаев Д.Д." },
        executor: { username: "darta", email: "darta@example.com", fullName: "Дартаев Д.Д." },
    },
    {
        id: 3,
        title: "Тестирование логики",
        description: "Проверить граничные случаи в API",
        status: "новая",
        type: "task",
        author: { username: "admin", email: "admin@example.com", fullName: "Админ А.А." },
        executor: { username: "petrov", email: "petrov@example.com", fullName: "Петров П.П." },
    },
    {
        id: 4,
        title: "Обновить документацию",
        description: "Сделать обновление README и API reference",
        status: "в работе",
        type: "doc",
        author: { username: "ivanov", email: "ivanov@example.com", fullName: "Иванов И.И." },
        executor: { username: "admin", email: "admin@example.com", fullName: "Админ А.А." },
    },
    {
        id: 5,
        title: "Настроить CI/CD",
        description: "Подключить Github Actions и деплой",
        status: "новая",
        type: "task",
        author: { username: "petrov", email: "petrov@example.com", fullName: "Петров П.П." },
        executor: { username: "ivanov", email: "ivanov@example.com", fullName: "Иванов И.И." },
    },
    {
        id: 6,
        title: "Создать модуль авторизации",
        description: "JWT, refresh token, роли",
        status: "в работе",
        type: "feature",
        author: { username: "admin", email: "admin@example.com", fullName: "Админ А.А." },
        executor: { username: "darta", email: "darta@example.com", fullName: "Дартаев Д.Д." },
    },
    {
        id: 7,
        title: "UI правки",
        description: "Исправить отступы, добавить тени",
        status: "завершена",
        type: "bug",
        author: { username: "petrov", email: "petrov@example.com", fullName: "Петров П.П." },
        executor: { username: "ivanov", email: "ivanov@example.com", fullName: "Иванов И.И." },
    },
    {
        id: 8,
        title: "Добавить логирование",
        description: "Записывать ошибки в файл",
        status: "в работе",
        type: "feature",
        author: { username: "darta", email: "darta@example.com", fullName: "Дартаев Д.Д." },
        executor: { username: "admin", email: "admin@example.com", fullName: "Админ А.А." },
    },
    {
        id: 9,
        title: "Отрисовка дашборда",
        description: "Сделать макет как в Jira",
        status: "новая",
        type: "task",
        author: { username: "admin", email: "admin@example.com", fullName: "Админ А.А." },
        executor: { username: "petrov", email: "petrov@example.com", fullName: "Петров П.П." },
    },
    {
        id: 10,
        title: "Интеграция с Kafka",
        description: "Настроить стриминг в хранилище",
        status: "в работе",
        type: "feature",
        author: { username: "darta", email: "darta@example.com", fullName: "Дартаев Д.Д." },
        executor: { username: "ivanov", email: "ivanov@example.com", fullName: "Иванов И.И." },
    }
];
